# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ohci_hcd" "ehci_pci" "ahci" "firewire_ohci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nixos--vg-root";
      fsType = "btrfs";
      options = "rw,ssd,space_cache,relatime";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/nixos--vg-home";
      fsType = "btrfs";
      options = "rw,ssd,space_cache,relatime";
    };

  fileSystems."/boot" =
    { device = "/dev/sda1";
      fsType = "vfat";
      options = "rw,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro,relatime";
    };

  swapDevices =
    [ { device = "/dev/dm-1"; }
    ];

  nix.maxJobs = 2;
}
